add: workManager
Aliibnabdul/HomeworkAA pull request #12
Opened 2021-02-13 22:00 UTC by Aliibnabdul

Homework 9: Background work

2021-02-14 19:10 UTC, Vladuken requested changes
Плюс минус прокомментил

2021-02-14 19:10 UTC, Vladuken commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.2.1'
мб лучше не даунгрейдить версию

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +    }
регистрацию воркменеджера можешь запихнуть в Application класс

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +    }
Ну, как минимум в данном случае как мне кажется будет лучше

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MoviesConstants.kt
> +    const val NOTIFICATION_TITLE = "WorkRequest Starting"
Мб вынести вещи которые в итоге будут пользователю показаны (то есть на UI) в строки?

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +        openAppIntent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP
вынеси в приватный метод типо createIntent или как нибудь так

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +        openAppIntent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP
или даже полностью вынеси это в метод createPendingIntent

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +            .addAction(notificationAction(CANCEL_WORK_ACTION))
а вот это можно вынести в метод createNotiofication

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +        mNotificationManager.notify(NOTIFICATION_ID, builder.build())
а вот это чтобы уже работало с нотификацией которую создашь

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +    }
вот это вот по идее может будет работать потому что регистрировать ресивер и создавать mNotificationManager ты будешь через один объект NotificationManager и в одном месте а закрывать через другой

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +        }
Я не сильно разбираюсь в ресиверах, но мне кажется что мб можно каким-то другим образом без ресивера - но. я не уверен

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsReceiver.kt
> +            when (action) {
![telegram-cloud-photo-size-2-5280524654366274126-y](https://user-images.githubusercontent.com/23121846/107886301-017c1100-6f10-11eb-84ec-90edb7da13d3.jpg)

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +        notificationsManager.showNotification(resources.getString(R.string.refreshWorker_has_started))
здесь можно использовать сразу applicationContext.getString

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +            }
вот это я немного не понимаю зачем, типо глайд он может же в оперативной памяти хранить, и твой прелат ничего в итоге не сделает, потому что когда ты откроешь приложение загрузка может по новой начаться.

Но вообще прикольно конечно такая оптимизация, но я хз зачем

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +                MovieEntity.fromDto(movieDto, index + indexOfLastMovieInDb + 1)
так, MovieEntity не должна знать про MovieDto, а должно происходить как мы уже обсуждали - сначала в доменную модель из MovieDto, потом в MovieEntity из доменной модели

2021-02-14 19:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +    }
на самом деле такое я бы тоже убрал когда-нибудь потом, или вынес в отдельную логику и переиспользовал, потому что как я понял, такая логика где то уже есть

2021-02-16 11:39 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +    }
Ссори. Ничего не понял в этом комментарии)

2021-02-16 13:57 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +        }
Не знаю как по другому с workManager.

2021-02-16 14:05 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +            }
Это для загрузки картинок когда приложение закрыто и некуда отображать. Потом если отрубить интернет и запустить приложение картинки отобразятся.

2021-02-16 15:22 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +                MovieEntity.fromDto(movieDto, index + indexOfLastMovieInDb + 1)
Это я тут просто прозевал в прошлый раз

2021-02-21 15:52 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +    }
Убери из MainActivity теперь старт WorkManager-a: потому что по идее он при старте приложения регистрируется

2021-02-21 15:57 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +            }
вынеси тогда в приватный метод, типо private fun preCacheImages

2021-02-21 16:10 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/workers/RefreshWorker.kt
> +    }
Смотри - ты этот ретиривер который сделал - сделал синглтоном, а так лучше не делать. 
Вместо этого ты можешь сделаь класс, который будет принимать себе в конструктор networkInterface и вместо того чтобы явно ссылаться на синглтон - прокинуть его в параметр конструктор MoviesRemoteMediator и вооще ты можешь его в свой Inject добавить 
![image](https://user-images.githubusercontent.com/23121846/108630880-3809dc80-7478-11eb-8054-812216d14e05.png)

и вот так
![image](https://user-images.githubusercontent.com/23121846/108630904-4fe16080-7478-11eb-9264-471a246333bb.png)

А в RefreshWorker просто поле сделать

![image](https://user-images.githubusercontent.com/23121846/108630934-80c19580-7478-11eb-8674-93da3cc25abc.png)

2021-02-21 16:19 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/notifications/NotificationsManager.kt
> +    }
Суть была в том что когда ты регистрируешь ресивер - ты делаешь это через один объект NotificationManager, который ты создаешь в RefreshWorker-е
А когда удаляешь регистрацию - то создаешь NotificationManager внутри ресивера- а это уже другой объект менеджера. 
Лучше сделать таким образом :

![image](https://user-images.githubusercontent.com/23121846/108631122-8b305f00-7479-11eb-989a-c31e67d032b5.png)
Потому что ресивер будет получать менеджер через конструктор - ну и это вот так выглядеть будет
![image](https://user-images.githubusercontent.com/23121846/108631170-a26f4c80-7479-11eb-9d83-5ac6cf3a4fc2.png)

2021-02-21 17:35 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +    }
Забыл

2021-02-21 18:00 UTC, merged