Homework 3
Aliibnabdul/HomeworkAA pull request #4
Opened 2020-11-29 12:43 UTC by Aliibnabdul

add: fragment movies list, fragment movie details
remove: movie details activity

2020-11-29 14:26 UTC, Vladuken requested changes
Прокомментил

Про стили если так удобнее можешь оставить , но лучше почитай про стили 

И еще avengers_img.png в webp сформатуруй

2020-11-29 14:26 UTC, Vladuken commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Это ненужная строчка

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
Перед тем как делать коммит можно автоотформатировать код через CTRL+ALT+L / Command+Option+L 

<img width="777" alt="image" src="https://user-images.githubusercontent.com/23121846/100542768-2b9d2b80-325d-11eb-817d-00f7b2b59e64.png">

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/drawable/age_limit_background.xml
> +<!--<shape-->
Удали закомментированнное

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/drawable/age_limit_background.xml
> +    <group>
<img width="601" alt="Screenshot 2020-11-29 at 16 14 57" src="https://user-images.githubusercontent.com/23121846/100542902-183e9000-325e-11eb-8444-0880d9a3e933.png">
кстати, если не ошибаюсь, то этот drawable используется еще и как background на экране детализации. Можешь его туда тоже добавить?

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/drawable/movie_item_frame.xml
> +        android:color="@color/movie_item_frame">
кажется здесь должна быть либо ширина меньше либо прозрачность цвета больше, потому невооруженным глазом видно, что разница достаточно большая  (первый скрин дизайн, второй у тебя)
<img width="278" alt="image" src="https://user-images.githubusercontent.com/23121846/100542999-a31f8a80-325e-11eb-99a9-8f6be106b471.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/23121846/100543008-b2063d00-325e-11eb-8e91-f5c03d49f094.png">

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/drawable/movie_item_frame.xml
> +        android:color="@color/movie_item_frame">
Кстати если прям сравнивать их рядом, то звездочки правее и текст 13+ должен быть потолще, остальное плюс минус норм

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/values/colors.xml
> +    <color name="location_icon">#FF3365</color>
некоторые цвета у тебя уже были в этом файле. 

Как мне кажется, с цветами можно просто назвать их так как они есть ,и на них ссылаться, не дублируя в самом файле colors

Убери дублирование цветов, и думаю их можно называть просто их названиями (как например у тебя уже выше в этом же файле сделано)

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/values/strings.xml
> +    <string name="movie_reviews">125 REVIEWS</string>
в строках можно убрать CAPS, сделать строку lowercase, а просто у той вьюхи на Которую ты вешаешь этот текст, добавить атрибут textAllCaps="true"

(там ниже тоже есть еще одна строка с капсом, ее тоже)

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesList.kt
> +    override fun onAttach(context: Context) {
Для удобства можно ставить методы жизненного цикла отсортированными в порядке вызова (типо onAttach раньше даже чем onCreateView а detach ближе к концу)

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesList.kt
> +        fun replaceFragment()
этот метод можно назвать по тому, что он делает

типо navigteToMovieDetails() 
так сразу станет удобнее читать и понятнее

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +    private val moviesListFragment = FragmentMoviesList()
убери эту строчку из полей класса MainActivity , и вызывай конструктор FragmentMovieList() уже в транзакции фрагмент менеджера. 

И еще лучше вместо того чтобы вызывать через конструктор, сделай статический метод FragmentMoviesList .newInstance() в companion object

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +                replace(R.id.fragments_container, FragmentMoviesDetails())
здесь тоже сделай FragmentMoviesDetails.newInstance()

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:gravity="start|center_vertical"
center будет достаточно

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:layout_height="297dp"
296

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:layout_marginEnd="4dp"
дздесь можно попробовать у гайдлайна который слева отступ поставить 8dp вместо 12 , 

А у этой вьюхи просто поставить margin=4dp (чтобы сработало на все стороны, а не только на layout_marginEnd )

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +    android:padding="2dp"
попробуй вместо того чтобы здесь хардкодить паддинг в 2дп, добавить его в  `@drawable/movie_item_frame`

https://stackoverflow.com/questions/30219120/view-with-a-border 
Второй ответ по ссылке:

```
<padding
    android:bottom="2dip"
    android:left="2dip"
    android:right="2dip"
    android:top="2dip" />

```

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        app:shapeAppearanceOverlay="@style/iv_back_image_corners"
как мне кажется потом запутаешься со стилями, но пусть пока так будет, потом можно будет отрефакторнуть

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        app:layout_constraintDimensionRatio="1:1"
из-за того что тут wrap_content - layout_constraintDimensionRatio работать не будет, но думаю лучше тут так и оставить, просто убрать layout_constraintDimensionRatio, либо поиграться с констрейнтами чтобы оно на разных строках квадратное всегда было

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        android:scaleX="0.7"
scale скелейлит внутреннее содержимое рейтинг бара, а размер он все такой же занимает

Попробуй как-нибудь сделать без скейла, тогда не придется  странныйе layout_constraintStart_toStartOf ставить и тогда тот баг с тем что звездочки криво отображаются пропадет.

Если не получится что то найти, то попробуй кастомный рейтинг бар использовать который я кидал в чатик

Либо пиши, будем думать(я просто сам с рейтингбаром не работал, сразу не приходит ничего на ум)

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        android:text="@string/movie_reviews"
как я уже писал в strings.xml 
сюда можно добавить textAllCaps а строку сделать lowercase

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        android:text="@string/movies_list_minutes"
десь тоже textAllCaps

2020-11-29 14:26 UTC, Vladuken commented on app/src/main/res/values/themes.xml
> +    <style name="iv_cast_corners">
Если тебе так удобно делать сейчас , то пусть так и будет, но в будущем придется рефакторить

Прям правильного-правильного подхода по вынесению в стили я не знаю и его скорее всего и нет, но этот мне кажется усложнит в будущем, когда экранов станет много

2020-11-29 15:07 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
Круть. А я пользовался Ctrl+alt+I

2020-11-29 16:06 UTC, Aliibnabdul commented on app/src/main/res/layout/movie_item.xml
> +        android:scaleX="0.7"
Долго над этим сидел, нашел 3 варианта уменьшить звезды до 8dp:
1. из чатика бар с png звездами - нужно городить свои звезды
2. из чатика кастом-бар с svg звездами - нужно городить класс плюс свои звезды
3. вариант со скейлом, просто его немного еще подвинуть за экран(вроде читал, что это не оч. хоршо)

2020-11-29 16:10 UTC, Aliibnabdul commented on app/src/main/res/layout/movie_item.xml
> +        android:text="@string/movie_reviews"
Не знал о таком. В чем выгода?

2020-11-29 16:22 UTC, Aliibnabdul commented on app/src/main/res/values/themes.xml
> +    <style name="iv_cast_corners">
Не понимаю, что рефакторить. У меня один стиль углов на 4 вьюхи. Вроде удобно искать и изменять.

2020-11-29 17:19 UTC, Aliibnabdul commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:layout_marginEnd="4dp"
Тогда исчезнет marginTop="27dp". Как поступить?

2020-11-29 17:32 UTC, Aliibnabdul commented on app/src/main/res/layout/movie_item.xml
> +        app:shapeAppearanceOverlay="@style/iv_back_image_corners"
Не знаю как по другому. Везде где видел углы для ShapeableImageView задаются через app:shapeAppearanceOverlay="@style/...

2020-12-01 22:52 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:layout_marginEnd="4dp"
Пока что можно добавить гайдлайн,
или вместо margin сделать 4 разных - marginTop,marginBottom, marginStart, marginEnd , в таком случае не переопределится. потому что каждому из них ты укажешь свой margin

2020-12-01 22:53 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        app:shapeAppearanceOverlay="@style/iv_back_image_corners"
Я это больше про именования стилей , с shapeAppearanceOverlay все ок

2020-12-01 22:55 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        android:text="@string/movie_reviews"
Плюсы в том, что у тебя в строковых ресурсах по сути лежит обычная строка, а за отображение ее капсом отвечает сама вьюха. 

Просто хорошая практика - так делать.

2020-12-01 22:56 UTC, Vladuken commented on app/src/main/res/values/themes.xml
> +    <style name="iv_cast_corners">
Я это тоже касательно неймингов - стили выносятся в основном для того чтобы переиспользовать их, а не просто вынести код (хотя так тоже можно)

2020-12-01 23:00 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        android:scaleX="0.7"
3 вариант плох тем, что скейл относительный и в итоге то что у тебя в лейауте самого item-а выглядит нормально, внутри другого лейаута уже съезжает
<img width="191" alt="image" src="https://user-images.githubusercontent.com/23121846/100806652-e6861e80-3441-11eb-98f0-c05fb0a969e4.png">

<img width="252" alt="image" src="https://user-images.githubusercontent.com/23121846/100806697-faca1b80-3441-11eb-9b67-35fb7688369b.png">


Мне кажется лучше всего 2й вариант. 
Можешь просто вынести класс с кастомной вьюхой в отдельный пакет. 
Из плюсов будет то что ты теперь можешь поставить иконки как в дизайне (то есть с небольшими закруглениями) и то что я так понимаю вьюха теперь будет нормально отрисовываться

2020-12-01 23:11 UTC, Vladuken commented on app/src/main/res/drawable/movie_item_frame.xml
> +        android:color="@color/movie_item_frame">
Так, заметил пару различий по дизайну еще -

1. У тебя там градиент на весь item стоит. Но там градиент только на картинке, а Title + длительность фильма уже на другом цвете.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/23121846/100807518-88f2d180-3443-11eb-9741-37691a3f854c.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/23121846/100807539-91e3a300-3443-11eb-8006-84df7ebee7d9.png">

2. Звездочки криво
3. у 13+ строки должен быть чуть темнее background и еще меньше marginTop
<img width="210" alt="image" src="https://user-images.githubusercontent.com/23121846/100807504-81cbc380-3443-11eb-823e-ae1c529bd0e3.png">
<img width="149" alt="image" src="https://user-images.githubusercontent.com/23121846/100807490-7c6e7900-3443-11eb-8c3b-f4d3f09100cc.png">

4. Сердечко и 13+ должны быть отцентрованны друг для друга, у тебя пока не так (плюс ощущение что сердечко должно быть чуть больше, но это субъективно уже )
<img width="611" alt="image" src="https://user-images.githubusercontent.com/23121846/100807430-5d6fe700-3443-11eb-96d3-319d0c225e72.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/23121846/100807480-74163e00-3443-11eb-9889-546fe7dad7b9.png">

2020-12-03 19:57 UTC, Vladuken requested changes

2020-12-03 19:57 UTC, Vladuken commented on app/src/main/res/values/colors.xml
> +    <color name="grey">#6D6D80</color>
у тебя уже есть такой цвет в colors.xml

2020-12-03 19:57 UTC, Vladuken commented on app/src/main/res/layout/movie_item.xml
> +        android:layout_height="14dp"
здесь можно height поставить 0dp чтобы она по высоте становилась такая же как и 13+ вьюха, тогда и сердце чуть побольше будет

2020-12-06 14:11 UTC, merged