add: recycler view
Aliibnabdul/HomeworkAA pull request #5
Opened 2020-12-06 15:00 UTC by Aliibnabdul

add recyclers

2020-12-06 18:42 UTC, Vladuken requested changes
Прокомментил

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +    private var castRecycler: RecyclerView? = null
У тебя есть binding - поэтому тебе не нужно никаких переменных на view хранить и можно сразу работать с переменной биндинга

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +            tvDescription.text = movie?.description
Есть небольшое предложение - сделать movie - nonNullable. Тогда у тебя здесь станет кода меньше и уберутся куча '?:' операторов, которые здесь особо и не нужны, потому что они обрабатывают не отсутствие конкретного поля у объекта, а отсутствие самого объекта.

Как вариант можно сделать 

`val movie: Movie? = arguments?.getParcelable(KEY_MOVIE_OBJECT)`
в
`val movie: Movie = arguments?.getParcelable(KEY_MOVIE_OBJECT)!!`

Но если захочешь, я могу прикольнее описать вариант, как сам делаю, но пока можно и так.

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
>      }
вот это тоже уберется как уберешь ссылку на castRecycler и будешь сразу работать с binding  объектом

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +            tvDescription.text = movie?.description
еще для удобства можно вынести весь код по настройке вьюхи в приватный метод , чтобы точно знать где у тебя информация о фильме инфлейтится, а где вся остальная работа происходит

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesList.kt
> +    private var recycler: RecyclerView? = null
убери

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesList.kt
> +    }
кстати, из интересного - ты можешь вместо  создания AdapterListInterface просто прикидывать в адаптер лямбду - в итоге кода станет меньше а результат такой же.

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesList.kt
> +    }
здесь сразу можно с биндингом работать

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +                    replace(R.id.fragments_container, FragmentMoviesDetails.createInstance(movie))
можно не переименовывать в createInstance, а просто оставить метод newInstance - конвенция такая прост)

и не забывай CTRL+SHIFT+L))

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/adapter/moviesList/MovieListAdapter.kt
> +}
вот это можно убрать ,просто сделав лямбду в конструкторе

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/adapter/moviesList/MovieListViewHolder.kt
> +        }
вот здесь можно воспользоваться магией котлина, и из if() вернуть drawable, а потом уже засетить 
Типо такого 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/23121846/101288651-ac819780-3808-11eb-9912-e21635390e68.png">

Или такого:
![Uploading image.png…]()

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/res/layout/cast_recycler_item.xml
> +        android:text="@string/movie_details_downey"
когда ты ставишь android:text- ты ставишь текст к каждой вьюшке
И если ты из кода не поменяешь его, то будет стоять этот текст. 

Вместо этого ты можешь использовать tools:text - и текст будет отображаться только в layout editor-е

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_details.xml
>              android:text="@string/movie_details_description"
по всему этому файлу можешь пройтись и там где текст динамический, поменять на tools:text="....."

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +        app:layout_constraintGuide_percent="0.5" />
центральный гайдлайн можешь теперь убрать, он не нужен

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/res/values/strings.xml
> -    <string name="movie_reviews">125 reviews</string>
те строки которые были захардкожены но уже не используются - можно убрать (это тайтлы фильма описание и прочее )

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/Movie.kt
> +    val detailsBAckImage: String,
опечатка

2020-12-06 18:42 UTC, Vladuken commented on app/src/main/res/drawable/ic_heart_unchecked.xml
> +</vector>
Попробуй вместо того чтобы делать второй drawable для иконки, которые только цветом отличается, поиграться с drawableTint

2020-12-07 10:11 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +            tvDescription.text = movie?.description
Asserted call мне не очень нравится, да и поля, приходящие из сети могут быть null. Было бы интересно увидеть правильное решение

2020-12-07 10:57 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/adapter/moviesList/MovieListViewHolder.kt
> +        }
Сделал. Только ссылка нерабочая

2020-12-16 22:40 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +            tvDescription.text = movie?.description
Тут логика такая, что раз уж мы отдаем Movie через аргументы, то это значит что Movie нам уже пришел где то извне. 

А это значит что единственная причина по которой на этом экране Movie может быть null - это потому что мы его забыли прокинуть извне. А это уже наш косяк, который если мы исправим, больше не возникнет.
Поэтому в таких случаях !! можно использовать. Но да, ты прав, !! лучше использовать как можно реже и только в случаях когда ты понимаешь то что приложение должно упасть в этом случае

2020-12-16 22:42 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +            tvDescription.text = movie?.description
И еще - я тут другому человеку описал как еще можно сделать красиво - вот скрин
<img width="740" alt="image" src="https://user-images.githubusercontent.com/23121846/102415350-1409c500-4009-11eb-9244-f76420c954e1.png">

2020-12-16 22:44 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/FragmentMoviesDetails.kt
> +            tvDescription.text = movie?.description
А касательно nullable полей которые приходят с бека - мы пока ориентируемся на то, что у нас все есть. добавить nullable - не проблема.

Также бывает еще такая штука как разделение на Data модель и Domain модель.

Опишу в двух словах пока что , но суть такая
Domain модель может быть с non-nullable полями
А в дате могут некоторые null приходить. 

И в результате мы когда маним Data модель которая пришла с бека, решаем как правильно заманить это в Domain.



Либо если наш Domain подразумевает что строка может быть nullable- то тогда можем сделать ее nullable.

2020-12-16 22:50 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/adapter/moviesList/MovieListViewHolder.kt
> +        }
Там примерно такая же штука.

Так, но я все-равно добавлю комментарий касательно кодстайла:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/23121846/102415838-ee30f000-4009-11eb-8451-9d54ff4169db.png">

if/else желательно всегда обрамлять фигурными скобочками - это хоть и больше строчек занимает, но куда удобнее читается

<img width="253" alt="image" src="https://user-images.githubusercontent.com/23121846/102415914-0bfe5500-400a-11eb-98c0-ea362ec3a682.png">

Касательно остальных случаем можно стайлгайды почитать или книгу CleanCode(если прям хочешь привыкнуть себя к прекрасному:D)

2020-12-19 03:12 UTC, merged