Architectures
Aliibnabdul/HomeworkAA pull request #8
Opened 2020-12-29 09:09 UTC by Aliibnabdul

2020-12-29 21:31 UTC, Vladuken requested changes
Прокомментил

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/MoviesRepository.kt
> +        list.singleOrNull { it.id == id }
Здесь я предлагаю (как минимум сейчас , а как максимум и потом) сделать Movie не nullable.
По той причине что так как мы условно этот id достаем из списка который получили с репозитория, то с даже чисто человеческой точки зрения мы можем быть уверенными что фильм у нас там есть.

поэтому предлагаю сделать что то типо одного из этих вариантов:

` fun getMovie(id: Int): Movie = list.find { it.id == id }!!` - вот этот возможно даже более стабильный - потому что он по документации возвращает нам первый элемент из списка в котором  `it.id == id `

`fun getMovie(id: Int): Movie = list.single { it.id == id }` - а вот этот возвращает только если этот элемент один (если же их 0 или больше 1 - то кидает ошибку)

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/MoviesRepository.kt
> +        }
я не сильно разбираюсь в корутинах, но в том же rx-е стараются реже ставить Потоки внутри логики, а больше отдают переключение потоков на уровень ViewModel.

По той причине, что условная вьюмодель не будет знать о том на каком потоке стартанула работа, и ему лучше самому решать , а не отдавать наугад

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/MoviesRepository.kt
> +        }
то есть это конечно можно еще обсудить, но я бы убрал из репозитория withContext(Dispatchers.Default)

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/MovieListAdapter.kt
> +class MovieListAdapter(private val listener: (Int) -> Unit) :
А вот здесь я бы оставил как было, чтобы в лямбде был Movie.

Потому что сам адаптер то у нас работает с Movie, и было бы логично что при клике по нему он возвращает нам Movie, а не его id

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/MoviesListViewModel.kt
> +    }
Смотри как можно сделать лучше:

Я там выше писал что Dispatcher лучше выбирать где то на уровне вьюмодели (или той штуки которая пользуется репозиторием). Поэтому здесь можно поставить диспатчер. 

А теперь более важное. 
Так как у нас теперь эта работа может быть не на UI потоке - то лучше в `mutableMoviesList` ставить Value не через присвоение, а через `postValue` , потому что пост работает из любого потока

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/FragmentMoviesDetails.kt
> +    private val movieDetailsViewModel: MovieDetailsViewModel by viewModels { ViewModelFactory() }
так, пришло время магии

Короче
 тебе нужно будет сделать по одной ViewModelFactory на каждую из вьюмоделей. 
 
 Для чего? Для того чтобы можно было прокинуть не только репозиторий в конструктор, но и id в конструктор.
 
 Я просто не работал много с ViewModelFactory и не знал как она работает, но сейчас немного посмотрел и небольшой спойлер как можно будет сделать:
Вьюмодель:
```
class MovieDetailsViewModel(
    repository: MoviesRepository,
    id: Int
) : ViewModel() {
    val movieLiveData: LiveData<Movie> = MutableLiveData(repository.getMovie(id))
}
```

фактори Вьюмодели:
```
class ViewModelFactory(
    private val id: Int
) : ViewModelProvider.Factory {

    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel?> create(modelClass: Class<T>): T = when (modelClass) {
        MovieDetailsViewModel::class.java -> MovieDetailsViewModel(MoviesRepository, id)
        else -> throw IllegalArgumentException("$modelClass is not registered ViewModel")
    } as T
}
```

И самая магия В фрагменте :
 ```
private val movieDetailsViewModel: MovieDetailsViewModel by viewModels {
        ViewModelFactory(arguments.movieIdBundle)
    }


```


Тогда нам можно будет убрать из вьюмодели этот метод refreshMovie, а просто прокинуть в конструктор - и вот это уже прям огонь!)

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/FragmentMoviesDetails.kt
>      }
вот это можно будет убрать благодаря параметру в конструкторе

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/FragmentMoviesDetails.kt
> +        fun newInstance(id: Int): FragmentMoviesDetails {
А вот тут уже как удобнее тебе можешь решить:

Есть два варианта:

1. Ты можешь рассматривать метод newInstance как тот что работает с именно ФИЛЬМАМИ, поэтому внутрь будет прикидываться Movie : `newInstance(movie: Movie)`, и в методе будет просто его id браться
2. А можешь рассматривать этот метод как тот что просто принимает в себя id-  и оставить как сейчас. Оба варианта прикольные и не сильно значимы в текущем контексте, но условно если первый выберешь, то у тебя не будет возможности кинуть какой то рандомную цифру, а всегда нужно будет какой то фильм

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +    private val moviesViewModel: MoviesListViewModel by viewModels { ViewModelFactory() }
Здесь тоже отдельный вьюмодел фактори для MoviesListViewModel

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MainActivity.kt
> +    override fun moveToFragment(id: Int) {
условно можешь даже здесь принимать Movie в параметре, а айпишник внутри метода доставать

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ViewModelFactory.kt
> +}
сделай две отдельные фактори для разных вьюмоделей

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +        moviesViewModel.refreshMoviesList(requireContext())
в будущем это пробрасывание контекста уберется

2020-12-29 21:31 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +        fun moveToFragment(id: Int)
вот этот метод думаю можно оставить чтобы он работал именно с Movie(но я там где то выше уже писал про это)

2020-12-30 09:51 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/data/MoviesRepository.kt
> +        }
Согласен. Вообще Retrofit гарантирует выполнение своих suspend функций на не main dispatcher, поэтому данное переключение излишнее.

2020-12-30 09:57 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/MovieListAdapter.kt
> +class MovieListAdapter(private val listener: (Int) -> Unit) :
Тогда класс Movie придется обратно делать Parcelable. Как поступить?

2020-12-30 10:06 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/MoviesListViewModel.kt
> +    }
Согласен. Вообще Retrofit гарантирует выполнение своих suspend функций на не main dispatcher, поэтому данное переключение излишнее.

2020-12-30 10:22 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/FragmentMoviesDetails.kt
> +    private val movieDetailsViewModel: MovieDetailsViewModel by viewModels { ViewModelFactory() }
Да круть! Только ты все за меня написал)

2020-12-30 10:28 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/FragmentMoviesDetails.kt
> +        fun newInstance(id: Int): FragmentMoviesDetails {
С id мне кажется лучше, т.к. при пробросе movie д.б. Parcelable и не факт что именно этот movie надо будет отобразить. Может быть придется загружать более детальный объект по id.

2021-01-09 12:31 UTC, merged