Homework 7: Networking
Aliibnabdul/HomeworkAA pull request #9
Opened 2021-01-18 15:22 UTC by Aliibnabdul

add: retrofit, paging adapter

2021-01-27 22:26 UTC, Vladuken requested changes
Прокомментил, теперь можно и спать)

2021-01-27 22:26 UTC, Vladuken commented on app/build.gradle
> +
Для BASE_URL можно не заводить отдельный Flavor, а делать сразу в buildTypes

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/res/layout/cast_recycler_item.xml
> +        app:layout_constraintDimensionRatio="1:1.3"
А почему теперь не 1 к 1?

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/MoviesListAdapter.kt
> +        }
Предлагаю здесь сделать что то типо такого:
  
   ```
     getItem(position)?.let{
            holder.onBind(it)
        }
```

Или вот так 
   ` getItem(position)?.let(holder::onBind)`

А листенер вообще прокидывать либо в onBind(), либо даже в конструктор ViewHolder-а
И ставить клик уже внутри onBind

Вот типо так:
![image](https://user-images.githubusercontent.com/23121846/106042642-63561180-60ee-11eb-8007-7f89865e8ea0.png)

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/MoviesApp.kt
> +        Injection.setup(this)
Предлагаю позже перейти на какой нибудь Koin/Dagger

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateViewHolder.kt
> +        binding.errorMsg.isVisible = loadState !is LoadState.Loading
```
 fun bind(loadState: LoadState) {
        
        fun showLoadingState(isLoading: Boolean) {
            binding.progressBar.isVisible = isLoading
            binding.retryButton.isVisible = !isLoading
            binding.errorMsg.isVisible = !isLoading
        }

        when (loadState) {
            is LoadState.NotLoading -> showLoadingState(false)
            is LoadState.Loading -> showLoadingState(true)
            is LoadState.Error -> {
                showLoadingState(false)
                binding.errorMsg.text = loadState.error.localizedMessage
            }
        }

    }
```

Можно использовать when для того чтобы обработать все случаи явно (и чтобы не рповерять на !is LoadState.Loading и прочее)

Еще можно внутри вьюхи просто запихнуть в контейнеры для loading и error состояния, тогда тебе просто нужно будет не каждую вьюху отдельно делать видимой/невидимой - а просто спрятать/показать контейнер

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateViewHolder.kt
> +        }
` binding.retryButton.setOnClickListener { retry() }`

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateViewHolder.kt
> +    retry: () -> Unit
`onRetryClicked`

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateViewHolder.kt
> +            val binding = LoadStateFooterBinding.bind(view)
```
 
            val binding = LoadStateFooterBinding.inflate(
                    LayoutInflater.from(parent.context),
                    parent,
                    false
            )
```

Здесь можно сразу вот так сделать, чтобы не инфлейтить вью отдельно и биндить ее отдельно

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateAdapter.kt
> +    private val retry: () -> Unit
тоже` onRetryClicked`

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +        app:layout_constraintBottom_toBottomOf="parent"/>
Предлагаю эти три вьюшки вобще убраь и не засорять ими xml - а сделать можно более красиво (я в коде фрагмента опишу)

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +            binding.tvCheckInternet.isVisible = loadState.source.refresh is LoadState.Error
```
when(loadState.source.refresh){
                is LoadState.NotLoading ->{
                    //Здесь бы тоже не менял видимость списка а сделал бы его всегда видимым
                    binding.rvMovies.isVisible = true
                } 
                is LoadState.Loading ->{
                    //Вот это я бы убрал потому что у тебя и так уже показывается что загрузка идет (в футере)
                    binding.progressBar.isVisible = true
                }
                is LoadState.Error ->{
                    //тут вообще AlertDialog бы исполльзовал  - тогда вот все эти вьюшки можно будет удалить и из xml
                    binding.retryButton.isVisible = true
                    binding.tvCheckInternet.isVisible = true
                }
            }
```

Но вообще вместо того что выше  я бы сделал вообще вот так:
```

if(loadState.source.refresh is LoadState.Error){
                AlertDialog.Builder(requireContext())
                        .setMessage("Какое либо сообщение можно и сообщение об ошибке сюда ")
                        .setPositiveButton("RETRY"){ _,_ ->
                            //тут клик обработать
                        }
                        .setCancelable(false)
                        .show()
                            
            }
```

Это будет более чистый способ
(Ну или можно опять запихнуть в контейнер вьюхи, чтобы у каждой из нее не менять видимость а только у контейнера)

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +            }
Это я бы убрал или как нибудь рефакторнул (за пейджинг не сильно шарю, так что возможно тут и норм, но выглядит не сильно красиво)

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +        search(query)
можно сразу 
`
 search("now_playing")`

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +        }
Есть предложение - на данном этапе немного упростить - полностью убрав search строку из уровней Фрагмента вьюмодели и даже датасорса, а просто захардкодить ее при запросе. 

После этого в вьюмодели сделать просто поле Flow<PagingData<Movie>> на которое фрагмент подпишется, и тогда не придется на фрагменте с джобами играться

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +    private lateinit var moviesListAdapter: MoviesListAdapter
```
  private val moviesListAdapter: MoviesListAdapter = MoviesListAdapter{
        listener.moveToFragment(it)
    }
```

Здесь можно сразу проинициализировать и удалить  lateinit

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +        binding.retryButton.setOnClickListener { moviesListAdapter.retry() }
вот это можно будет убрать в пользу AlertDialog
(ну и вообще на будущее - старайся упрощать вьюхи, чтобы она как можно реже содержала в себе кучу других вьюх которые ты будешь прятать/показывать в зависимости от какого то события (ну или выноси их в контейнеры))

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/MoviesListViewModel.kt
> +    private var currentQueryValue: String? = null
предлагаю пока что и отсюда убрать query , оставить только публичную Flow<PagingData<Movie>>

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/MoviesListViewModel.kt
> +    fun getFlowPagingData(queryString: String): Flow<PagingData<Movie>> {
вот этот метод тоже можно убрать и вынести в init

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/FragmentMovieDetails.kt
> +    private fun initViews(movieWithActors: MovieWithActors) {
В этом классе есть небольшая притензия только к MovieWithActors - я бы попробовал их оставить разделенными и отдельнми модельками. Но я это в другом классе опишу

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/CastListViewHolder.kt
> +    fun onBind(actor: ActorEntity) {
Ладно попробую в трех словах описать здесь

Смотри - у нас есть моделька Актера которая содержит в себе данные об актере - это данные для отображения 
Но ты ее еще используешь чтобы в бд сохранять

А как насчет разнести и сделать пару моделей 

Условно 
Actor - чистая моделька которая хранит в себе данные и они отображаются у нас на экране
ActorEntity - служит только для сохранения в базу данных и мапится в/из Actor
ActorDto - это этот же актер, но который приходит с сервера, и тоже мапится в Actor

Сейчас накидаю как это примерно может выглядеть на простой 

![image](https://user-images.githubusercontent.com/23121846/106054403-04e45f80-60fd-11eb-8681-548ca6ad3fe2.png)

Это позволит нам спрятать подальше зависимости от ретрофита и рума, и если нам понадобтся что-то поменять - так будет проще

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/CastListViewHolder.kt
> +    fun onBind(actor: ActorEntity) {
С остальными модельками тоже так сделай:
![image](https://user-images.githubusercontent.com/23121846/106054586-4b39be80-60fd-11eb-8d00-bb561a9142ff.png)
Ну и их можно по разным пакетам раскидать 
Чистые модельки в domain
Для бека в network или как еще назовешь
Для бд в db или room или как захочешь назовешь

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesFakeDatabase.kt
> +}
Это можно удалить или пометить как @Deprecated

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDatabase.kt
> +    // before calling build(), call .fallbackToDestructiveMigration().
Комментарии удали

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDatabase.kt
> +//                .fallbackToDestructiveMigration()
Вот это можешь оставиь на самом деле - потому что так намного проще жить и миграции нужны только в проде.
Ну либо оставить и пометить как TODO Remove

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDatabase.kt
> +            }
Вот этот метод лучше переписать как нибудь попонятнее

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDatabase.kt
> +        private var INSTANCE: MoviesDatabase? = null
можешь выпендриться и попробовать сюда вмето nullable lateinit подставить, 

и проверять как`  ::INSTANCE.isInitialized`

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDao.kt
> +    @Insert//(onConflict = OnConflictStrategy.REPLACE)
Ты можешь в модельке MovieEntity использовать как primarykey не твой дополнительный автогенерируемый, а тот что получаешь с бека (если он уникальный)

И тогда без проблем OnConflictStratesy.Replace можно будет юзать

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDao.kt
> +    @Query("SELECT * from movies_table ORDER BY `index` ASC")
По идее если здесь убрать order by то оно будет в том порядке в котором вставлялось, так что возможно ббудет проще

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDao.kt
> +    suspend fun insertAll(moviesList: List<Movie>)
ну и да, попробуй сделать для Movie отдельную румовскую модельку MovieEntity (или MovieRoom, или как сам решишь назвать)

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDao.kt
> +    suspend fun getMoviesWithActors() :List<MovieWithActors>
Кстати вот эту румовскую модельку MovieWitActor ты тоже можешь маппить в доменные Movie и Actor, и с ними уже работать на вьюмодели

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/MoviesDao.kt
> +interface MoviesDao {
Кстати, можешь раскидать и сделать несколькко Dao 

То есть Dao это обычно для CRUD операций с одной моделькой, 
так что можно сделать MovieDao, ActorDao и тд, а не пихать все методы в один

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/MoviesListResponse.kt
> +
Думаю это можно на два класса раскидать, только держи их отдльным пакетом - те что для нетворка в одном, те что для бд в другом, так будет легче и меньше шансов что запутаешься

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/MovieWithActors.kt
> +)
На самом деле я обычно @Relation в руме стараюсь избегать, но сюда было бы неплохо добавить метод маппинга в Pair<Movie,List<Actors>>, или как то так, и не юззать эту модель на экране и вьюмодели, потому что она для бд используеся

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/MovieDetailsResponse.kt
> +    val runtime: Int? = null,
не нужно самому =null указывать

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/Movie.kt
> +@Entity(tableName = "movies_table")
Разбей на чистую Movie и MovieEntity для бд

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/CastResponse.kt
> +	val cast: List<Actor>,
Здесь тоже юзай не чистого актера, а ActorResponse, или ActorDto, как назовешь

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/ActorEntity.kt
> +    var profilePath: String? = null
убери явное присвоение null из конструктора (хотя это в редких случаях удобно, но лучше сначала убрать, апотом уже если понадобится добавить, чем наоборот)

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/models/Actor.kt
> +    var profilePath: String? = null
здесь тоже - классу достаточно знать что он может быть nullable, а по дефолту нет смысла ставить null

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/NetworkInterface.kt
> +    @GET("movie/{query}?api_key=528872f1b83a56c38aafb7c9fd9dc105&language=en-US")
ты можешь вынести api_key тоже в @Query - и тут уже поставить его по дефолту , и вынести в API_KEY

вот так например

![image](https://user-images.githubusercontent.com/23121846/106060544-3e20cd80-6105-11eb-9983-292c312b263c.png)


URI в @GET - должна быть максимально простой

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/NetworkInterface.kt
> +    @GET("movie/{query}?api_key=528872f1b83a56c38aafb7c9fd9dc105&language=en-US")
Ну и собственно во всех остальных методах класса так же сделай

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/MoviesRepository.kt
> +        if (isNetworkConnected(context)) {
Попробуй здесь убрать проверку на наличие интернета , и вместо этого просто работать с этой штукой так словно интернет есть

я бы проверку интернета делал на самом верху либо вообще не делал и просто обрабатывал ошибки.

да, как еще вариант - можно try{} catch{} сделать и в конце finally вернуть из бд

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/MoviesRepository.kt
> +                    .mapToActorsEntityList(id)
и вот от mapToActorsEntityList лучше тоже избавиться, а вынести как я расписывал в ActorEntity companion object метод from(actor:Actor) и тут просто список замаппить

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/RemoteKeysDao.kt
> +}
Короче тут я не лезу, потому что не до конца понимаю зачем эти RemoteKeys, но коммент прост оставлю себе на будущее, вдруг начну понимать)

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/db/RemoteKeys.kt
> +)
Здесь тоже не буду лезтьб. Единственное - мб вынести все эти штуки рядом, если он до сих пор не вынесены

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/extensions/Exts.kt
> +}
Это можно убрать в ActorEntity companion object - ну и избався над экстеношоном над листом и просто над одним элементом экстешн напиши

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/extensions/Exts.kt
> +
Здесь тоже можно избавиться от экстеншона на списке, и вынести его в компанион обджект ResultItem

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/extensions/Exts.kt
> +
либо убрать либо в NetworkExt.kt

2021-01-27 22:26 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/data/MoviesRemoteMediator.kt
> +class MoviesRemoteMediator(
Честно говоря, я сюда даже лезть боюсь, сам сегодня пытался что то типо такого сделать  - ничего не вышло, забил, и сделал кширование без ремоут медиатора) Ну я собственно скинул ссылку можешь глянуть в том проекту

2021-01-31 11:55 UTC, Aliibnabdul commented on app/src/main/res/layout/cast_recycler_item.xml
> +        app:layout_constraintDimensionRatio="1:1.3"
Разные картинки и как ни подгоняй все равно какие-то режет либо сверху либо снизу

2021-01-31 12:07 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/MoviesApp.kt
> +        Injection.setup(this)
Я к этому потиху подхожу

2021-01-31 16:49 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateViewHolder.kt
> +        }
Это в кодлабе так пишут

2021-01-31 16:54 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateViewHolder.kt
> +    retry: () -> Unit
Что тут не так?

2021-01-31 17:50 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +        search(query)
Оставил чтобы поиск прикрутить

2021-02-02 11:39 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +        }
.collectLatest и suspend fun submitData(it) могут быть вызваны только из корутины. И еще searchJob здесь для прерывания прошлого запроса, если он не завершен. Или может я тебя не совсем понимаю?

2021-02-02 11:56 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +    private lateinit var moviesListAdapter: MoviesListAdapter
Словил крэш. Сначала listener должен инициализироваться контекстом в onAttach(). Может сделать moviesListAdapter by lazy?

2021-02-03 09:14 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/CastListViewHolder.kt
> +    fun onBind(actor: ActorEntity) {
Сделал так для FragmentMovieDetails, все ок. А для FragmentMoviesList не знаю как переделать PagingSource<Int, MovieEntity> в PagingSource<Int, Movie>.

2021-02-03 10:27 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/db/MoviesDao.kt
> +    @Insert//(onConflict = OnConflictStrategy.REPLACE)
В MovieEntity мой primarykey "index" autogenerate = false, он уникальный и задается как порядковый номер и не зависит от страницы, т.е. если в базу загружено 3 страницы, то индексы будут от 0 до 60, по 20 айтемов на странице. Он нужен для добавления в бд следующей страницы с индексами 61-80, иначе без него сбивается порядок айтемов. Без этого индекса меняется порядок отображения при добавлении новой страницы в бд. Без индекса бд видимо отдает со своей сортировкой по movieId и адаптер все перетасовывает.

2021-02-03 11:02 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/db/MoviesDao.kt
> +    @Query("SELECT * from movies_table ORDER BY `index` ASC")
Убрал, работает, похоже по дефолту отдает с сортировкой по primary key index

2021-02-05 10:24 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/db/MoviesDatabase.kt
> +        private var INSTANCE: MoviesDatabase? = null
Выпендрился), вроде и так и так понятно

2021-02-05 10:35 UTC, Aliibnabdul commented on app/src/main/java/com/example/homeworkAA/db/RemoteKeysDao.kt
> +}
To tell Room how to fetch the next and previous pages from the network when it reaches to the start or end of the current page. https://www.raywenderlich.com/12244218-paging-library-for-android-with-kotlin-creating-infinite-lists

2021-02-10 19:52 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/LoadingStateViewHolder.kt
> +        }
https://kotlinlang.org/docs/reference/operator-overloading.html

Это называется operator function -
тот же invoke() позволяет котлину вызывать этот метод как () - то есть без слова invoke

2021-02-10 20:02 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/moviesList/FragmentMoviesList.kt
> +            binding.tvCheckInternet.isVisible = loadState.source.refresh is LoadState.Error
Так - касательно этого - вынеси захардкоженные строки в strings.xml
<img width="395" alt="image" src="https://user-images.githubusercontent.com/23121846/107564740-d59d1a80-6bf3-11eb-9a29-82e53c34daff.png">

Плюс возможно вместо is используй when - да, будут пустые блоки кода, но зато будет видны все возможные варианты
<img width="464" alt="image" src="https://user-images.githubusercontent.com/23121846/107564904-05e4b900-6bf4-11eb-995e-db3b18d6e40c.png">

2021-02-10 20:20 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +        app:layout_constraintBottom_toBottomOf="parent"/>
Переименуй еще id который через нижнее подчеркивание в camelCase

2021-02-10 21:01 UTC, Vladuken commented on app/src/main/java/com/example/homeworkAA/ui/movieDetails/CastListViewHolder.kt
> +    fun onBind(actor: ActorEntity) {
Предлагаю пока на это забить - но как далее попробую предложить вариант

2021-02-10 21:11 UTC, merged